import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { LogIn, Plus, RefreshCw, Save, ShieldCheck, Trash2, X } from 'lucide-react'

type Account={id:number;name:string;account_name:string;enabled:boolean;game_exe:string;launch_args:string;window_title:string;state:string;task:string;progress:number;message:string;world:string;has_password:boolean;auto_login:boolean;auto_reconnect:boolean;auto_daily:boolean;max_reconnect_attempts:number;max_backup_switches:number;reconnect_delay_seconds:number;backup_account_ids:number[];updated:string}
type Form={name:string;account_name:string;password:string;window_title:string;game_exe:string;launch_args:string;auto_login:boolean;auto_reconnect:boolean;auto_daily:boolean;max_reconnect_attempts:number;max_backup_switches:number;reconnect_delay_seconds:number;backup_account_ids:number[]}
const blank:Form={name:'',account_name:'',password:'',window_title:'梦幻西游',game_exe:'',launch_args:'',auto_login:true,auto_reconnect:true,auto_daily:false,max_reconnect_attempts:3,max_backup_switches:2,reconnect_delay_seconds:15,backup_account_ids:[]}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(path,{headers:{'Content-Type':'application/json'},...init});if(!res.ok)throw Error(await res.text());return res.json()}
export default function Accounts(){
 const [rows,setRows]=useState<Account[]>([]),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<number|null>(null),[open,setOpen]=useState(false),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false)
 const load=async()=>{setLoading(true);try{setRows((await api<{results:Account[]}>('/api/accounts/')).results)}catch{setNotice('账号接口连接失败')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const edit=(a?:Account)=>{setEditing(a?.id??null);setForm(a?{name:a.name,account_name:a.account_name,password:'',window_title:a.window_title,game_exe:a.game_exe,launch_args:a.launch_args,auto_login:a.auto_login,auto_reconnect:a.auto_reconnect,auto_daily:a.auto_daily,max_reconnect_attempts:a.max_reconnect_attempts,max_backup_switches:a.max_backup_switches,reconnect_delay_seconds:a.reconnect_delay_seconds,backup_account_ids:a.backup_account_ids}:blank);setOpen(true)}
 const save=async(e:FormEvent)=>{e.preventDefault();try{await api(editing?`/api/accounts/${editing}/`:'/api/accounts/',{method:editing?'PATCH':'POST',body:JSON.stringify(form)});setNotice('账号已保存，密码仅以密文写入数据库');setOpen(false);setEditing(null);load()}catch{setNotice('账号保存失败')}}
 const remove=async(id:number)=>{if(!confirm('确定删除该账号？'))return;try{await api(`/api/accounts/${id}/`,{method:'DELETE'});setNotice('账号已删除');load()}catch{setNotice('删除失败')}}
 const action=async(id:number,actionName:'login'|'reconnect')=>{try{const r=await api<{result?:{status?:string;reason?:string}}>(`/api/accounts/${id}/action/`,{method:'POST',body:JSON.stringify({action:actionName})});setNotice(actionName==='login'?`登录执行：${r.result?.status??'已提交'}`:'已启动重连/备用账号切换流程');load()}catch{setNotice(`${actionName==='login'?'登录':'重连'}操作失败`)}}
 return <section className="panel accountPanel"><div className="panelHead"><div><h2>账号管理</h2><span>MySQL 持久化 · 密码 Fernet 加密 · 多次重连后自动切换备用账号</span></div><div className="panelActions"><button className="ghost" onClick={load}><RefreshCw size={14}/>刷新</button><button className="primary" onClick={()=>edit()}><Plus size={14}/>添加账号</button></div></div>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}<div className="tableWrap"><table><thead><tr><th>ID</th><th>账号</th><th>游戏角色</th><th>状态</th><th>任务</th><th>重连</th><th>备用账号</th><th>自动登录</th><th>操作</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.id}</td><td><b>{a.account_name||'-'}</b><div className="muted">{a.name}</div></td><td>{a.window_title}</td><td><span className={`status ${a.state==='IDLE'?'success':a.state==='DISCONNECTED'||a.state==='ERROR'?'danger':'warning'}`}>{a.state}</span></td><td>{a.task||'空闲'}</td><td>{a.max_reconnect_attempts}次 / {a.reconnect_delay_seconds}s</td><td>{a.backup_account_ids.length} 个</td><td>{a.auto_login?'开启':'关闭'}</td><td><div className="rowActions"><button onClick={()=>edit(a)}>编辑</button><button onClick={()=>action(a.id,'login')}><LogIn size={12}/>登录</button><button onClick={()=>action(a.id,'reconnect')}><RefreshCw size={12}/>重连</button><button onClick={()=>remove(a.id)}><Trash2 size={12}/>删除</button></div></td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={9} className="emptyRow">暂无账号，点击“添加账号”。</td></tr>}</tbody></table></div>{open&&<AccountModal form={form} setForm={setForm} editing={editing} accounts={rows} save={save} close={()=>setOpen(false)}/>}</section>
}
function AccountModal({form,setForm,editing,accounts,save,close}:{form:Form;setForm:(f:Form)=>void;editing:number|null;accounts:Account[];save:(e:FormEvent)=>void;close:()=>void}){return <div className="modalMask"><form className="taskModal" onSubmit={save}><div className="modalHead"><div><h2>{editing?'编辑游戏账号':'添加游戏账号'}</h2><span><ShieldCheck size={14}/> 密码不会返回前端，只在后端解密给登录执行器</span></div><button type="button" onClick={close}><X/></button></div><div className="formGrid"><Field label="账号名称"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="登录账号"><input required value={form.account_name} onChange={e=>setForm({...form,account_name:e.target.value})}/></Field><Field label="登录密码"><input type="password" value={form.password} placeholder={editing?'留空表示不修改密码':'请输入密码'} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="窗口标题"><input value={form.window_title} onChange={e=>setForm({...form,window_title:e.target.value})}/></Field><Field wide label="游戏 EXE"><input value={form.game_exe} onChange={e=>setForm({...form,game_exe:e.target.value})} placeholder="C:\\梦幻西游\\xyq.exe"/></Field><Field wide label="启动参数"><input value={form.launch_args} onChange={e=>setForm({...form,launch_args:e.target.value})}/></Field><Field label="最大重连次数"><input type="number" min="0" max="20" value={form.max_reconnect_attempts} onChange={e=>setForm({...form,max_reconnect_attempts:Number(e.target.value)})}/></Field><Field label="最大备用切换"><input type="number" min="0" max="20" value={form.max_backup_switches} onChange={e=>setForm({...form,max_backup_switches:Number(e.target.value)})}/></Field><Field label="重连间隔(秒)"><input type="number" min="1" max="3600" value={form.reconnect_delay_seconds} onChange={e=>setForm({...form,reconnect_delay_seconds:Number(e.target.value)})}/></Field><Field wide label="备用账号"><select multiple value={form.backup_account_ids.map(String)} onChange={e=>setForm({...form,backup_account_ids:Array.from(e.target.selectedOptions).map(x=>Number(x.value))})}>{accounts.filter(a=>a.id!==editing).map(a=><option key={a.id} value={a.id}>{a.name} / {a.account_name}</option>)}</select></Field><Field label="自动登录"><input type="checkbox" checked={form.auto_login} onChange={e=>setForm({...form,auto_login:e.target.checked})}/></Field><Field label="自动重连"><input type="checkbox" checked={form.auto_reconnect} onChange={e=>setForm({...form,auto_reconnect:e.target.checked})}/></Field><Field label="自动日常"><input type="checkbox" checked={form.auto_daily} onChange={e=>setForm({...form,auto_daily:e.target.checked})}/></Field></div><div className="modalFoot"><button type="button" className="ghost" onClick={close}>取消</button><button className="primary"><Save size={14}/>保存账号</button></div></form></div>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={wide?'wide':''}>{label}{children}</label>}
