import { ElementType, useEffect, useMemo, useState } from 'react'
import { Activity, ChevronRight, LayoutDashboard, Menu, RefreshCw, ShieldCheck, Smartphone, Users, Radio, X } from 'lucide-react'
import Accounts from './Accounts'
import ControlPanel from './ControlPanel'
import LiveMonitor from './LiveMonitor'

type Overview={counts:{total:number;active:number;pending:number;done:number;cancelled:number};workers:any[];recent_logs:{id:number;level:string;event:string;message:string;created:string;account:string}[]}
type Nav={key:string;label:string;icon:ElementType}
const nav:Nav[]=[{key:'dashboard',label:'运行总览',icon:LayoutDashboard},{key:'live',label:'实时监控',icon:Radio},{key:'accounts',label:'账号管理',icon:Users},{key:'control',label:'多开控制',icon:Smartphone}]
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{headers:{'Content-Type':'application/json',...(init?.headers||{})},...init});if(!r.ok)throw Error(await r.text());return r.json()}

export default function App(){
 const [page,setPage]=useState('dashboard'),[mobileOpen,setMobileOpen]=useState(false),[overview,setOverview]=useState<Overview|null>(null),[notice,setNotice]=useState(''),[backendOnline,setBackendOnline]=useState(false)
 const load=async()=>{try{const data=await api<Overview>('/api/overview/');setOverview(data);setBackendOnline(true);setNotice('')}catch{setBackendOnline(false);setNotice('后端未连接，请先启动 Django 服务')}}
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[])
 const running=useMemo(()=>overview?.workers?.filter(x=>!['STOPPED','DISCONNECTED','ERROR'].includes(x.state)).length??0,[overview])
 const go=(key:string)=>{setPage(key);setMobileOpen(false)}
 return <div className="appShell">
  <header className="topbar"><button className="mobileMenu" onClick={()=>setMobileOpen(v=>!v)} aria-label="菜单"><Menu size={21}/></button><div className="brandBlock"><div className="brandGlyph">GM</div><div><div className="brandTitle">梦幻西游 AI 主控</div><div className="brandSub">多开 · 自动化 · 运营控制台</div></div></div><nav className="topNav">{nav.map(({key,label,icon:Icon})=><button key={key} onClick={()=>go(key)} className={page===key?'topNavItem active':'topNavItem'}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="topActions"><span className={`systemStatus ${backendOnline?'online':'offline'}`}><i/>{backendOnline?'后端在线':'后端离线'}</span><button className="iconButton" onClick={load} title="刷新"><RefreshCw size={17}/></button><div className="avatar">GM</div></div></header>
  <aside className={mobileOpen?'sidebar open':'sidebar'}><div className="sideInner"><div className="mobileSideHead"><b>控制台</b><button onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>{nav.map(({key,label,icon:Icon})=><button key={key} onClick={()=>go(key)} className={page===key?'sideItem active':'sideItem'}><Icon size={16}/>{label}<ChevronRight size={13}/></button>)}<div className="sideInfo"><div><i className={`onlineDot ${backendOnline?'online':'offline'}`}/>{backendOnline?'系统运行':'后端离线'}</div><span>账号 {overview?.counts.total??0} · 活跃 {running}</span></div></div></aside>
  <main className="mainContent">{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}{page==='dashboard'&&<Dashboard overview={overview} running={running} refresh={load}/>} {page==='live'&&<LiveMonitor/>}{page==='accounts'&&<Accounts/>}{page==='control'&&<ControlPanel/>}</main>
  <footer className="mobileFooter"><span>梦幻西游 AI 主控</span><span>v2.5</span></footer>
 </div>
}

function Dashboard({overview,running,refresh}:{overview:Overview|null;running:number;refresh:()=>void}){const workers=overview?.workers??[];const disconnected=workers.filter(x=>['DISCONNECTED','ERROR'].includes(x.state)).length;const active=workers.filter(x=>!['STOPPED','DISCONNECTED','ERROR'].includes(x.state)).length;return <div className="dashboardPage"><section className="hero"><div><div className="eyebrow">CONTROL CENTER</div><h1>运行总览</h1><p>统一查看账号、窗口、任务与异常状态。所有控制均调用当前后端接口，不显示未接入功能。</p></div><button className="primary" onClick={refresh}><RefreshCw size={15}/>刷新状态</button></section><section className="statGrid"><Stat title="账号总数" value={overview?.counts.total??0} icon={Users} tone="blue"/><Stat title="运行中" value={active} icon={Activity} tone="green"/><Stat title="掉线 / 异常" value={disconnected} icon={ShieldCheck} tone="red"/><Stat title="已完成任务" value={overview?.counts.done??0} icon={LayoutDashboard} tone="purple"/></section><section className="dashboardGrid"><div className="panel"><div className="panelHead"><div><h2>账号运行状态</h2><span>10 秒自动刷新</span></div><span>{running} 个客户端运行中</span></div><div className="workerCards">{workers.length?workers.map(w=><div className="workerCard" key={w.id}><div className="workerTop"><b>{w.name}</b><Status state={w.state}/></div><div className="workerMeta">{w.account_name||'未设置登录账号'} · {w.world||'未识别地图'}</div><div className="workerTask">{w.task||'空闲'}<span>{w.progress??0}%</span></div><div className="miniProgress"><i style={{width:`${Math.min(100,Math.max(0,w.progress??0))}%`}}/></div>):<Empty text="暂无账号，先到账号管理添加账号"/>}</div></div><div className="panel logPanel"><div className="panelHead"><div><h2>最新日志</h2><span>后端 Log</span></div></div>{overview?.recent_logs?.length?<div className="logList">{overview.recent_logs.map(x=><div className="logRow" key={x.id}><span className={`logDot ${x.level==='ERROR'?'danger':x.level==='WARN'?'warn':'ok'}`}/><div><b>{x.event}</b><p>{x.message}</p></div><small>{new Date(x.created).toLocaleTimeString('zh-CN',{hour12:false})}</small></div>)}</div>:<Empty text="暂无运行日志"/>}</div></section></div>}
function Stat({title,value,icon:Icon,tone}:{title:string;value:number;icon:ElementType;tone:string}){return <div className={`statCard ${tone}`}><div className="statIcon"><Icon size={19}/></div><div><span>{title}</span><b>{value}</b></div></div>}
function Status({state}:{state:string}){const bad=['DISCONNECTED','ERROR'].includes(state),ok=!['STOPPED','DISCONNECTED','ERROR'].includes(state);return <span className={`status ${bad?'danger':ok?'success':'muted'}`}><i/>{state||'STOPPED'}</span>}
function Empty({text}:{text:string}){return <div className="emptyState">{text}</div>}