import { ElementType, FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, Bell, BookOpen, Box, CheckSquare, ChevronDown, ClipboardList, FilePlus2, FileText, Home, Inbox, Package, Search, Settings, ShieldCheck, UserRound, Users, X, XCircle } from 'lucide-react'
import emblemCrop from './assets/gm-emblem-crop.png'
import cityCrop from './assets/server-city-crop.png'

type Task={id:number;name:string;type:string;type_label:string;status:string;status_label:string;condition:string;description:string;rewards:string;knowledge_key:string;progress:number;publisher:string;created:string}
type Overview={counts:{total:number;active:number;pending:number;done:number;cancelled:number};recent_logs:{id:number;level:string;event:string;message:string;created:string;account:string}[];workers:{id:number;name:string;state:string;task:string;progress:number;message:string}[]}
const types=[['MAIN','主线任务'],['SIDE','支线任务'],['DAILY','日常任务'],['ACTIVITY','活动任务'],['HIDDEN','隐藏任务'],['SPECIAL','特殊任务']]
const statuses=[['DRAFT','草稿'],['PENDING','待审核'],['ACTIVE','进行中'],['DONE','已完成'],['CANCELLED','已取消']]
const empty={name:'',type:'DAILY',status:'DRAFT',condition:'',description:'',rewards:'',knowledge_key:'',publisher:'GM001'}
const navItems:{icon:ElementType;label:string}[]=[{icon:Home,label:'首页'},{icon:Users,label:'玩家管理'},{icon:ClipboardList,label:'任务管理'},{icon:Package,label:'物品管理'},{icon:BarChart3,label:'数据统计'},{icon:Settings,label:'系统设置'}]
async function api<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(path,{headers:{'Content-Type':'application/json'},...init});if(!res.ok)throw Error('请求失败');return res.json()}
const format=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-'
const typeTone:Record<string,string>={MAIN:'red',SIDE:'green',DAILY:'blue',ACTIVITY:'purple',HIDDEN:'amber',SPECIAL:'pink'}

export default function App(){
 const [rows,setRows]=useState<Task[]>([]),[overview,setOverview]=useState<Overview|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[type,setType]=useState(''),[editing,setEditing]=useState<Task|null>(null),[modal,setModal]=useState(false),[form,setForm]=useState(empty),[hits,setHits]=useState<{file:string;excerpt:string}[]>([]),[notice,setNotice]=useState('')
 const load=async()=>{try{const p=new URLSearchParams();if(query)p.set('q',query);if(type)p.set('type',type);if(status)p.set('status',status);const [tasks,summary]=await Promise.all([api<{results:Task[]}>(`/api/tasks/?${p}`),api<Overview>('/api/overview/')]);setRows(tasks.results);setOverview(summary)}catch{setNotice('无法连接后端 API，请启动 Django 服务') }}
 useEffect(()=>{load()},[])
 const counts=useMemo(()=>overview?.counts??{total:0,active:0,pending:0,done:0,cancelled:0},[overview])
 const close=()=>{setModal(false);setEditing(null);setForm(empty);setHits([])}
 const edit=(t?:Task)=>{setEditing(t??null);setForm(t?{...t}:empty);setHits([]);setModal(true)}
 const save=async(e:FormEvent)=>{e.preventDefault();try{await api(editing?`/api/tasks/${editing.id}/`:'/api/tasks/',{method:editing?'PATCH':'POST',body:JSON.stringify(form)});close();setNotice('任务已保存');load()}catch{setNotice('保存失败')}}
 const transition=async(id:number,action:string)=>{try{await api(`/api/tasks/${id}/action/`,{method:'POST',body:JSON.stringify({action})});setNotice('状态已更新');load()}catch{setNotice('操作失败')}}
 const remove=async(id:number)=>{if(confirm('确定删除此任务？')){await api(`/api/tasks/${id}/`,{method:'DELETE'});setNotice('任务已删除');load()}}
 const searchKnowledge=async()=>{if(!form.knowledge_key)return;setHits((await api<{results:{file:string;excerpt:string}[]}>(`/api/knowledge/search/?q=${encodeURIComponent(form.knowledge_key)}`)).results)}
 return <div className="appShell"><header className="topbar"><div className="brandBlock"><img className="brandMark" src={emblemCrop} alt="GM"/><div><div className="brandTitle">GM任务管理系统</div><div className="brandSub">游戏运营管理后台</div></div></div><nav className="topNav">{navItems.map(({icon:Icon,label})=><button className={label==='任务管理'?'topNavItem active':'topNavItem'} key={label}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="topActions"><div className="notif"><Bell size={19}/><i>12</i></div><div className="notif"><Inbox size={19}/><i>5</i></div><div className="avatar">GM</div><div className="profile"><b>GM001</b><span><i className="onlineDot"/>在线</span></div><ChevronDown size={16}/></div></header>
 <aside className="sidebar"><div className="sideInner"><Side title="任务管理" items={['任务列表','创建任务','任务模板','任务审核','任务日志']} onCreate={()=>edit()}/><Side title="任务分类" items={types.map(x=>x[1])}/><div className="serverScene" style={{backgroundImage:`url(${cityCrop})`}}/><div className="serverCard"><div className="serverTitle">当前服务器</div><div className="serverName">梦幻西游 · 再续前缘</div><div className="serverState"><span className="dot on"/>运行中</div><div className="serverVersion">版本：v2.3.0 · xyq-skills 已接入</div></div></div></aside>
 <main className="mainContent"><section className="filterBar"><label>任务名称<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="请输入任务名称"/></label><label>任务类型<select value={type} onChange={e=>setType(e.target.value)}><option value="">全部类型</option>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>任务状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="dateFilter">创建时间<input placeholder="开始日期"/><span>至</span><input placeholder="结束日期"/></label><button className="primary" onClick={load}><Search size={15}/>查询</button><button className="ghost" onClick={()=>{setQuery('');setType('');setStatus('');setTimeout(load)}}>重置</button></section>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 <section className="kpiGrid"><Kpi icon={ClipboardList} title="任务总数" value={counts.total} tone="blue" trend="+12"/><Kpi icon={Activity} title="进行中" value={counts.active} tone="green" trend="+8"/><Kpi icon={CheckSquare} title="待审核" value={counts.pending} tone="amber" trend="-3"/><Kpi icon={ShieldCheck} title="已完成" value={counts.done} tone="purple" trend="+7"/><Kpi icon={XCircle} title="已取消" value={counts.cancelled} tone="red" trend="-2"/></section>
 <section className="panel taskPanel"><div className="panelHead"><div><h2>任务列表</h2><span>实时同步 · 共 {rows.length} 条记录</span></div><div className="panelActions"><button className="ghost">批量操作 <ChevronDown size={14}/></button><button className="ghost">导出数据</button><button className="primary" onClick={()=>edit()}><FilePlus2 size={14}/>创建任务</button></div></div><div className="tableWrap"><table><thead><tr><th><input type="checkbox"/></th><th>任务ID</th><th>任务名称</th><th>任务类型</th><th>发布人</th><th>接取条件</th><th>状态</th><th>进度</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><input type="checkbox"/></td><td>{String(t.id).padStart(6,'0')}</td><td className="nameCell">{t.name}</td><td><span className={`tag ${typeTone[t.type]??'blue'}`}>{t.type_label}</span></td><td>{t.publisher}</td><td>{t.condition||'-'}</td><td><span className={`status ${t.status==='ACTIVE'?'success':t.status==='PENDING'?'warning':t.status==='CANCELLED'?'danger':'info'}`}>{t.status_label.replace('运行中','进行中')}</span></td><td>{t.progress?<div className="progressCell"><div className="progress"><i style={{width:`${t.progress}%`}}/></div><span>{t.progress}%</span></div>:'-'}</td><td>{format(t.created)}</td><td><div className="rowActions"><button onClick={()=>edit(t)}>编辑</button>{t.status==='DRAFT'&&<button onClick={()=>transition(t.id,'submit')}>提交</button>}{t.status==='PENDING'&&<button onClick={()=>transition(t.id,'approve')}>审核</button>}{t.status==='ACTIVE'&&<button onClick={()=>transition(t.id,'complete')}>完成</button>}<button onClick={()=>remove(t.id)}>删除</button></div></td></tr>)}{!rows.length&&<tr><td className="emptyRow" colSpan={10}>暂无任务，点击“创建任务”开始配置。</td></tr>}</tbody></table></div><div className="tableFoot"><span>显示第 1 到第 {rows.length} 条记录</span><div className="pager"><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>…</button><button>20</button><button>10条/页 <ChevronDown size={12}/></button></div></div></section>
 <section className="bottomGrid"><Chart/><Distribution total={counts.total} rows={rows}/><div className="panel noticePanel"><div className="panelHead slim"><h2>系统公告</h2><button className="linkBtn">更多</button></div><ul>{(overview?.recent_logs.length?overview.recent_logs.map(x=>`${x.event} · ${x.message}`):['2024年5月20日 版本更新公告','服务器维护通知','新活动【端午节】即将开启','违规玩家处理公告','任务系统优化说明']).slice(0,5).map((x,i)=><li key={x}><span>• {x}</span><time>{['05-20','05-19','05-18','05-17','05-16'][i]}</time></li>)}</ul></div></section></main>
 {modal&&<TaskModal form={form} setForm={setForm} editing={editing} save={save} close={close} hits={hits} search={searchKnowledge}/>}</div>
}
function Side({title,items,onCreate}:{title:string;items:string[];onCreate?:()=>void}){return <div className="navSection"><div className="sectionTitle">{title}<ChevronDown size={14}/></div>{items.map((x,i)=><button onClick={x==='创建任务'?onCreate:undefined} className={i===0&&title==='任务管理'?'sideItem active':'sideItem'} key={x}>{i===0?<FileText size={14}/>:<Box size={13}/>} {x}</button>)}</div>}
function Kpi({icon:Icon,title,value,tone,trend}:{icon:ElementType;title:string;value:number;tone:string;trend:string}){return <div className={`kpi ${tone}`}><div className="kpiIcon"><Icon size={19}/></div><div><div className="kpiTitle">{title}</div><div className="kpiValue">{value}<span className="unit">个</span></div><div className="kpiTrend">较昨日 <b>{trend}⌄</b></div></div></div>}
function Chart(){return <div className="panel chartPanel"><div className="panelHead slim"><div><h2>任务统计</h2><span>最近7天</span></div><button className="selectLite">最近7天 <ChevronDown size={12}/></button></div><div className="lineChart"><div className="yAxis"><span>100</span><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div><svg viewBox="0 0 420 150" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#1890ff" stopOpacity=".38"/><stop offset="100%" stopColor="#1890ff" stopOpacity="0"/></linearGradient></defs><path d="M0 85 C35 50 45 98 72 68 S117 45 130 55 175 60 190 38 228 52 245 64 274 70 296 61 331 55 345 69 375 75 395 48 420 40 L420 150 L0 150Z" fill="url(#area)"/><path d="M0 85 C35 50 45 98 72 68 S117 45 130 55 175 60 190 38 228 52 245 64 274 70 296 61 331 55 345 69 375 75 395 48 420 40" fill="none" stroke="#4aa3ff" strokeWidth="2"/></svg><div className="xAxis"><span>05-14</span><span>05-15</span><span>05-16</span><span>05-17</span><span>05-18</span><span>05-19</span><span>05-20</span></div></div><div className="chartLegend"><i className="legendDot blue"/>任务数量</div></div>}
function Distribution({total,rows}:{total:number;rows:Task[]}){const data=types.map(([k,l])=>({l,n:rows.filter(x=>x.type===k).length}));return <div className="panel donutPanel"><div className="panelHead slim"><h2>任务类型分布</h2></div><div className="donutRow"><div className="donut"><div className="donutHole"><b>{total}</b><span>任务总数</span></div></div><div className="legendList">{data.map((x,i)=><div key={x.l}><i className={`c ${['red','green','blue','purple','amber','slate'][i]}`}/>{x.l}<span>{x.n} {total?`(${(x.n/total*100).toFixed(1)}%)`:''}</span></div>)}</div></div></div>}
function TaskModal({form,setForm,editing,save,close,hits,search}:{form:typeof empty;setForm:(x:typeof empty)=>void;editing:Task|null;save:(e:FormEvent)=>void;close:()=>void;hits:{file:string;excerpt:string}[];search:()=>void}){return <div className="modalMask"><form className="taskModal" onSubmit={save}><div className="modalHead"><div><h2>{editing?'编辑任务':'创建 GM 任务'}</h2><span>从 xyq-skills 检索官方玩法资料作为配置依据</span></div><button type="button" onClick={close}><X/></button></div><div className="formGrid"><Field label="任务名称"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="任务分类"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="接取条件"><input value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}/></Field><Field label="初始状态"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="知识库关键词"><div className="knowledgeInput"><input value={form.knowledge_key} onChange={e=>setForm({...form,knowledge_key:e.target.value})}/><button type="button" className="ghost" onClick={search}>检索</button></div></Field><Field label="任务奖励"><input value={form.rewards} onChange={e=>setForm({...form,rewards:e.target.value})}/></Field><Field wide label="任务说明"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div>{hits.length>0&&<div className="knowledgeResults"><b>知识库命中</b>{hits.slice(0,2).map(x=><div key={x.file}><small>{x.file}</small><p>{x.excerpt.slice(0,180)}…</p></div>)}</div>}<div className="modalFoot"><button type="button" className="ghost" onClick={close}>取消</button><button className="primary">保存任务</button></div></form></div>}
function Field({label,children,wide}:{label:string;children:ReactNode;wide?:boolean}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}
