import { useEffect, useState } from 'react'
import { CheckCircle2, LayoutGrid, RefreshCw, ShieldAlert, Sparkles, Square, Play } from 'lucide-react'
type Account={id:number;name:string;account_name:string;state:string;character_slot:number;role_name:string;team_priority:number;is_team_leader:boolean;auto_story_skip:boolean;auto_battle:boolean;battle_template:string;equipment_policy:string}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...init});if(!r.ok)throw Error(await r.text());return r.json()}
export default function ControlPanel(){
 const [rows,setRows]=useState<Account[]>([]),[selected,setSelected]=useState<number[]>([]),[mode,setMode]=useState<'single'|'multi'>('single'),[columns,setColumns]=useState(2),[width,setWidth]=useState(960),[height,setHeight]=useState(540),[notice,setNotice]=useState(''),[health,setHealth]=useState<any[]>([]),[loading,setLoading]=useState(false)
 const load=async()=>{try{setRows((await api<{results:Account[]}>('/api/accounts/')).results)}catch{setNotice('账号接口连接失败')}}
 const check=async()=>{try{const r=await api<{status:string;accounts:any[]}>('/api/multibox/health/',{method:'POST',body:JSON.stringify({account_ids:selected.length?selected:undefined})});setHealth(r.accounts||[]);setNotice(`健康检查：${r.status}`)}catch{setNotice('健康检查失败')}}
 useEffect(()=>{load();check()},[])
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);const all=rows.length>0&&selected.length===rows.length
 const start=async()=>{const ids=mode==='single'?selected.slice(0,1):selected;if(!ids.length){setNotice('请先选择账号');return}setLoading(true);try{const r=await api<any>('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'start',mode,account_ids:ids,columns,width,height,gap:8})});setNotice(`${mode==='single'?'单开':'多开'}已启动：${r.result.account_ids?.length??ids.length} 个客户端`);setTimeout(load,1200)}catch{setNotice('启动失败')}finally{setLoading(false)}}
 const stop=async()=>{if(!selected.length){setNotice('请先选择账号');return}try{await api('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'stop',account_ids:selected})});setNotice('已提交停止');load()}catch{setNotice('停止失败')}}
 const arrange=async()=>{try{await api('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'arrange',account_ids:selected,columns,width,height,gap:8})});setNotice('窗口排列计划已刷新')}catch{setNotice('窗口排列失败')}}
 const rolePlan=async()=>{try{const r=await api<{result:{account_id:number;role:string;character_slot:number}[]}>('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'role_plan',account_ids:selected,recommended_roles:['辅助','输出','输出','输出','输出']})});setNotice(r.result.map(x=>`#${x.account_id} ${x.role} · 角色${x.character_slot}`).join(' / ')||'暂无推荐')}catch{setNotice('推荐失败')}}
 return <section className="controlPage"><div className="panel controlHero"><div><div className="eyebrow">MULTI-BOX CONTROL</div><h2>多开控制中心</h2><p>单人只启动一个客户端；多开按队伍顺序启动并排列窗口。角色、剧情、战斗和装备策略由账号配置决定。</p></div><div className="controlHeroActions"><button className="ghost" onClick={check}><RefreshCw size={14}/>健康检查</button><button className="primary" onClick={start} disabled={loading}><Play size={14}/>{loading?'启动中':'启动选中'}</button></div></div>
 <div className="controlGrid"><div className="panel controlSettings"><div className="panelHead"><div><h2>运行配置</h2><span>只显示当前已实现的控制项</span></div></div><div className="settingsGrid"><label>运行模式<select value={mode} onChange={e=>setMode(e.target.value as 'single'|'multi')}><option value="single">单人</option><option value="multi">五开 / 多开</option></select></label><label>排列列数<input type="number" min="1" max="5" value={columns} onChange={e=>setColumns(Number(e.target.value))}/></label><label>窗口宽度<input type="number" min="320" max="1920" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><label>窗口高度<input type="number" min="240" max="1080" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label></div><div className="quickActions"><button className="ghost" onClick={rolePlan}><Sparkles size={14}/>推荐队伍角色</button><button className="ghost" onClick={arrange}><LayoutGrid size={14}/>重新排列窗口</button><button className="dangerButton" onClick={stop}><Square size={13}/>停止选中</button></div>{notice&&<div className="toast">{notice}</div>}</div>
 <div className="panel healthPanel"><div className="panelHead"><div><h2>多开健康状态</h2><span>窗口级检测</span></div><span>{health.length} 个</span></div><div className="healthList">{health.length?health.map((x:any,i)=><div className="healthRow" key={x.account_id??i}><span className={x.status==='OK'?'healthOk':'healthBad'}>{x.status==='OK'?<CheckCircle2 size={16}/>:<ShieldAlert size={16}/>}</span><div><b>账号 #{x.account_id}</b><small>{x.message||x.reason||x.status}</small></div><strong>{x.status}</strong></div>):<div className="emptyState">暂无检测结果，点击“健康检查”。</div>}</div></div></div>
 <div className="panel accountRunPanel"><div className="panelHead"><div><h2>启动队列</h2><span>已选择 {selected.length} / {rows.length}</span></div><button className="ghost" onClick={load}><RefreshCw size={14}/>刷新</button></div><div className="mobileCards"><div className="selectAll"><label><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:rows.map(x=>x.id))}/>全选</label><span>{mode==='single'?'单人模式只取第一个选中账号':'多开模式按选择顺序启动'}</span></div>{rows.map(a=><div className={`accountRunCard ${selected.includes(a.id)?'selected':''}`} key={a.id}><label className="checkCell"><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/></label><div className="runMain"><div className="workerTop"><b>{a.name}</b><span className="status muted"><i/>{a.state}</span></div><div className="workerMeta">{a.account_name} · 第{a.character_slot}角色 · {a.role_name||'自动推荐'}{a.is_team_leader?' · 队长':''}</div><div className="runTags"><span>剧情 {a.auto_story_skip?'跳过':'保留'}</span><span>战斗 {a.auto_battle?'自动':'手动'}</span><span>{a.battle_template}</span><span>{a.equipment_policy}</span></div></div></div>)}</div></div></section>
}
