import { useEffect, useState } from 'react'

type Account={id:number;name:string;account_name:string;state:string;character_slot:number;role_name:string;team_priority:number;is_team_leader:boolean;auto_story_skip:boolean;auto_battle:boolean;battle_template:string;equipment_policy:string}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...init});if(!r.ok)throw Error(await r.text());return r.json()}

export default function ControlPanel(){
 const [rows,setRows]=useState<Account[]>([]),[selected,setSelected]=useState<number[]>([]),[mode,setMode]=useState<'single'|'multi'>('single'),[columns,setColumns]=useState(2),[notice,setNotice]=useState('')
 const load=async()=>{try{setRows((await api<{results:Account[]}>('/api/accounts/')).results)}catch{setNotice('账号接口连接失败')}}
 useEffect(()=>{load()},[])
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
 const start=async()=>{const ids=mode==='single'?selected.slice(0,1):selected;if(!ids.length){setNotice('请先选择账号');return}try{const r=await api<{result:{status:string;account_ids:number[]};roles:{account_id:number;role:string;character_slot:number}[]}>('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'start',mode,account_ids:ids,columns})});setNotice(`${mode==='single'?'单开':'多开'}已提交：${r.result.account_ids.length} 个账号`)}catch{setNotice('启动失败')}}
 const stop=async()=>{if(!selected.length){setNotice('请先选择账号');return}try{await api('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'stop',account_ids:selected})});setNotice('已提交停止')}catch{setNotice('停止失败')}}
 const rolePlan=async()=>{try{const r=await api<{result:{account_id:number;role:string;character_slot:number}[]}>('/api/accounts/control/',{method:'POST',body:JSON.stringify({action:'role_plan',account_ids:selected,recommended_roles:['辅助','输出','输出','输出','输出']})});setNotice(r.result.map(x=>`#${x.account_id} ${x.role} · 角色${x.character_slot}`).join(' / '))}catch{setNotice('推荐失败')}}
 return <section className="panel"><div className="panelHead"><div><h2>多开控制中心</h2><span>单开只启动一个客户端；多开按队伍顺序启动并自动排列窗口</span></div></div><div className="controlBar"><label>运行模式<select value={mode} onChange={e=>setMode(e.target.value as 'single'|'multi')}><option value="single">单人</option><option value="multi">五开/多开</option></select></label><label>排列列数<input type="number" min="1" max="5" value={columns} onChange={e=>setColumns(Number(e.target.value))}/></label><button className="primary" onClick={start}>启动选中</button><button className="ghost" onClick={stop}>停止选中</button><button className="ghost" onClick={rolePlan}>角色推荐</button></div>{notice&&<div className="toast">{notice}</div>}<div className="tableWrap"><table><thead><tr><th>选择</th><th>账号</th><th>状态</th><th>角色槽位</th><th>定位</th><th>队长</th><th>剧情跳过</th><th>自动战斗</th><th>战斗模板</th><th>装备策略</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/></td><td><b>{a.name}</b><div className="muted">{a.account_name}</div></td><td>{a.state}</td><td>第 {a.character_slot} 个</td><td>{a.role_name||'自动推荐'}</td><td>{a.is_team_leader?'是':'否'}</td><td>{a.auto_story_skip?'开启':'关闭'}</td><td>{a.auto_battle?'开启':'关闭'}</td><td>{a.battle_template}</td><td>{a.equipment_policy}</td></tr>)}{!rows.length&&<tr><td colSpan={10} className="emptyRow">暂无账号</td></tr>}</tbody></table></div></section>
}
