import { useEffect, useState } from 'react'
import { Camera, Link2, RefreshCw, ScanLine, Square } from 'lucide-react'

type Win={hwnd:number;title:string;left:number;top:number;right:number;bottom:number}
type Props={accountId?:number}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...init});if(!r.ok)throw Error(await r.text());return r.json()}

export default function DesktopConsole({accountId=1}:Props){
 const [windows,setWindows]=useState<Win[]>([]),[bound,setBound]=useState<number|null>(null),[image,setImage]=useState(''),[runtime,setRuntime]=useState<any>(null),[message,setMessage]=useState('尚未扫描游戏窗口'),[busy,setBusy]=useState(false)
 const scan=async()=>{setBusy(true);try{const r=await api<{available:boolean;windows:Win[]}>('/api/desktop/windows/');setWindows(r.windows||[]);setMessage(r.windows?.length?`发现 ${r.windows.length} 个游戏窗口`:'没有发现“梦幻西游”窗口')}catch{setMessage('扫描失败，请确认后端运行在 Windows 环境')}finally{setBusy(false)}}
 const bind=async(hwnd:number)=>{try{await api('/api/desktop/select/',{method:'POST',body:JSON.stringify({account_id:accountId,hwnd})});setBound(hwnd);setMessage(`账号 #${accountId} 已绑定窗口 ${hwnd}`);await snapshot()}catch{setMessage('窗口绑定失败')}}
 const snapshot=async()=>{try{const r=await api<any>(`/api/desktop/${accountId}/snapshot/`);setImage(r.image||'');setRuntime(r.runtime);setBound(r.window.hwnd);setMessage(`截图成功：${r.window.title}`)}catch{setMessage('截图失败：窗口可能已关闭')}}
 const step=async()=>{setBusy(true);try{const r=await api<any>(`/api/desktop/${accountId}/step/`,{method:'POST'});setRuntime(r.runtime);setMessage(`Dry-run：${r.event?.action||'STEP'} · ${r.event?.message||''}`);await snapshot()}catch{setMessage('单步观察失败')}finally{setBusy(false)}}
 useEffect(()=>{scan()},[])
 return <section className="panel desktopConsole"><div className="panelHead"><div><h2>桌面客户端联调</h2><span>单账号测试模式 · Dry-run</span></div><button className="ghost" onClick={scan} disabled={busy}><RefreshCw size={14}/>扫描窗口</button></div><div className="desktopGrid"><div className="windowPicker"><div className="sectionTitle"><ScanLine size={15}/>游戏窗口</div>{windows.length?windows.map(w=><div className={`windowRow ${bound===w.hwnd?'selected':''}`} key={w.hwnd}><div><b>{w.title}</b><small>HWND {w.hwnd} · {w.right-w.left}×{w.bottom-w.top}</small></div><button className="ghost" onClick={()=>bind(w.hwnd)}><Link2 size={13}/>{bound===w.hwnd?'已绑定':'绑定'}</button></div>):<div className="emptyState">{message}</div>}</div><div className="previewPane"><div className="sectionTitle"><Camera size={15}/>实时截图</div><div className="screenshotBox">{image?<img src={image} alt="梦幻西游窗口截图"/>:<div className="emptyState">绑定窗口后点击刷新截图</div>}</div><div className="previewActions"><button className="ghost" disabled={!bound} onClick={snapshot}><Camera size={14}/>刷新截图</button><button className="primary" disabled={!bound||busy} onClick={step}><ScanLine size={14}/>单步观察</button><button className="dangerButton" disabled={!bound} onClick={()=>{setBound(null);setImage('');setMessage('已解除本地绑定')}}><Square size={13}/>解除</button></div></div></div><div className="runtimeReadout"><div><b>账号 #{accountId}</b><span>{message}</span></div>{runtime&&<div className="runtimeMetrics"><span>状态 <b>{runtime.state}</b></span><span>置信度 <b>{Math.round((runtime.confidence||0)*100)}%</b></span><span>{runtime.running?'运行中':'未运行'}</span></div>}</div></section>
}
